#page title
page_title                                :                                   # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1524569359                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                  # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A Starbucks secret menu companion.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Yon Montoto                                
your_link                                 : https://github.com/Yonodactyl/iOS-Portfolio                     
your_city                                 : Orlando, Florida                                
email_address                             : yon.montoto@gmail.com
facebook_username                         :                                           
instagram_username                        : drinkslyapp
twitter_username                          : yonodactyl
github_username                           : yonodactyl
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Discover.
    description                           : Discover your next go-to drink without the need to experiment. I have tried them all for you!
    fontawesome_icon_name                 : compass
    
  - title                                 : Favorite.
    description                           : When you find your favorite drink save it for later viewing. No need for blurry photos you found on the internet.
    fontawesome_icon_name                 : heart

  - title                                 : Order.
    description                           : Each drink comes with the exact directions to order it. No more anxiety when the barista ask what you want!
    fontawesome_icon_name                 : clone



# Theme Settings
topbar_color                              : "#FBFBFB"
topbar_transparency                       : 0.2
topbar_title_color                        : "#323232"

cover_image                               : assets/drinkslybackdrop.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#FBFBFB"
cover_overlay_transparency                : 0.85

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#FBFBFB"

link_color                                : "#FF2D55"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#323232"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FF2D55"
feature_icons_background_color            : "#F1F1F1"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
